const tracks = [
  {id:'omen',number:1,title:'Omen',chapter:'I — Les signes',chapterId:1,color:'#7352ff',symbol:'◐',mood:'Prophétie, présage, porte sombre.',description:'« Omen » annonce l’arrivée de Ramsès24 : entre banger, ambition, blessures et trahisons, il transforme son passé en force pour révéler *Philosophie Romaricaine*.'},
  {id:'heartbreak',number:2,title:'Heartbreak',chapter:'I — Les signes',chapterId:1,color:'#d94956',symbol:'♡',mood:'Cœur fissuré, pluie rouge, espace émotionnel.',description:'« Heartbreak » raconte un amour brisé qui transforme la déception de Ramsès24 en douleur, haine et volonté de ne plus jamais se laisser atteindre.'},
  {id:'deroute',number:3,title:'Déroute',chapter:'I — Les signes',chapterId:1,color:'#c08d55',symbol:'↯',mood:'Route brisée, panneaux contradictoires.',description:'« Déroute » exprime une descente sous pression, entre doute religieux, trahisons, colère et perte de repères, jusqu’à la rupture avec le monde.'},
  {id:'only-on-the-night',number:4,title:'Only on the Night',chapter:'I — Les signes',chapterId:1,color:'#5a91d6',symbol:'☾',mood:'Ville nocturne, lune, néons.',description:'« Only on the Night » raconte une rencontre nocturne qui apaise un cœur solitaire, avant de basculer dans le désespoir puis de choisir finalement la vie.'},
  {id:'ramses24',number:5,title:'Ramsès24',chapter:'II — L’identité',chapterId:2,color:'#d8a969',symbol:'R',mood:'Identité, trône, symbole central.',description:'« Ramsès24 » est un hymne d’affirmation où Ramsès24 revendique son identité, ses origines et son ascension, en se présentant comme une force unique et impossible à dépasser.'},
  {id:'ah-bah-wsh',number:6,title:'Ah bah wsh',chapter:'II — L’identité',chapterId:2,color:'#ef9b37',symbol:'!',mood:'Énergie spontanée, rue, humour.',description:'« Ah bah wsh » mélange l’affirmation de l’ADN artistique de Ramsès24, ses influences, son quotidien et sa révolte contre l’école, les attentes et ceux qui doutent de lui.'},
  {id:'on-est-pas-pareil',number:7,title:'On est pas pareil',chapter:'II — L’identité',chapterId:2,color:'#8c63c7',symbol:'◫',mood:'Miroir divisé, deux personnalités.',description:'« On n’est pas pareil » est un morceau d’affirmation et de provocation où Ramsès24 revendique sa différence, son orgueil et sa capacité à rester debout malgré les difficultés.'},
  {id:'14-fevrier',number:8,title:'14 Février',chapter:'II — L’identité',chapterId:2,color:'#c95872',symbol:'✧',mood:'Souvenirs, amour, calendrier, rose fanée.',description:'« 14 Février » raconte une déclaration d’amour rejetée qui transforme l’espoir de Ramsès24 en douleur, haine et inspiration artistique.'},
  {id:'faux-frere',number:9,title:'Faux frère',chapter:'II — L’identité',chapterId:2,color:'#6f6a87',symbol:'◒',mood:'Masque, duplicité, ombres.',description:'« Faux frère » raconte la trahison d’anciens amis et la revanche de Ramsès24, qui transforme ses blessures, ses nuits d’insomnie et ses épreuves en force, en art et en réussite.'},
  {id:'avant-ton-depart',number:10,title:'Avant ton départ',chapter:'III — Les mémoires et les fantômes',chapterId:3,color:'#d8a969',symbol:'10',mood:'Espace mémoriel, lumière chaude, archive familiale.',description:'« Avant ton départ » est un hommage poignant à son père disparu, où Ramsès24 mêle réussite, manque et douleur face à l’absence de celui dont il voulait obtenir la fierté.'},
  {id:'paranormal-r24',number:11,title:'Paranormal R24',chapter:'III — Les mémoires et les fantômes',chapterId:3,color:'#63b6af',symbol:'⌁',mood:'Glitch, fantômes numériques, signaux inconnus.',description:'« Paranormal R24 » est une démonstration monumentale où Ramsès24 mêle flow, séduction, ego et énergie drill pour affirmer une présence hors norme.'},
  {id:'who-are-you-bella',number:12,title:'Who are you Bella ?',chapter:'III — Les mémoires et les fantômes',chapterId:3,color:'#d7c3ff',symbol:'?',mood:'Enquête, silhouette mystérieuse, interrogation.',description:'« Who are you Bella ? » raconte une rencontre née de messages, transformée en rendez-vous magique puis en déclaration d’amour réciproque.'},
  {id:'mutonchaku',number:13,title:'無頓着 (Mutonchaku)',chapter:'III — Les mémoires et les fantômes',chapterId:3,color:'#adc5be',symbol:'無',mood:'Minimalisme japonais, calme, détachement.',description:'« 無頓着 (Mutonchaku) » exprime une errance sombre entre amour perdu, solitude, trahison et références animées, tandis que Ramsès24 transforme sa douleur en force et en quête de réussite.'},
  {id:'la-vie-est-hard',number:14,title:'La vie est hard',chapter:'IV — Le système',chapterId:4,color:'#87909a',symbol:'▥',mood:'Ville verticale, pluie, obstacles, béton.',description:'« La vie est hard » raconte la recherche d’argent et de travail, tout en mêlant humour, amour maternel, absence du père et méfiance envers un monde rempli de mensonges.'},
  {id:'la-melo-24',number:15,title:'La mélo 24',chapter:'IV — Le système',chapterId:4,color:'#85d3d6',symbol:'∿',mood:'Piano, vibration, mélodie lumineuse.',description:'« La mélo 24 » marque la sortie de l’ombre de Ramsès24, qui révèle une facette mélodique et lumineuse en transformant ses peines en énergie et en groove.'},
  {id:'ma-vie-html',number:16,title:'Ma_vie.html',chapter:'IV — Le système',chapterId:4,color:'#65d587',symbol:'</>',mood:'Code, terminal futuriste, fenêtre système.',description:'« Ma_vie.html (La tech !) » transforme la vie de Ramsès24 en programme à reconstruire : il archive ses douleurs, corrige ses erreurs et lance une nouvelle version de lui-même.'},
  {id:'oklm',number:17,title:'ΩKLM',chapter:'IV — Le système',chapterId:4,color:'#a68cff',symbol:'Ω',mood:'Identité cachée, symbole Ω, miroir cosmique.',description:'« ΩKLM (Who are you Ramsès ?) » dévoile la naissance de l’identité Ramsès24, son histoire, sa philosophie, ses origines et sa transformation de la timidité en singularité artistique.'},
  {id:'commoner',number:18,title:'Commoner',chapter:'V — Le vide et le jeu',chapterId:5,color:'#bf8d65',symbol:'≋',mood:'Peuple, humanité, contraste entre roi et personne ordinaire.',description:'« Commoner » présente Ramsès24 comme un homme du peuple devenu une anomalie du rap, portant la voix des réalités quotidiennes tout en bouleversant le système par son identité et son flow.'},
  {id:'macrovoid',number:19,title:'Macrovoid',chapter:'V — Le vide et le jeu',chapterId:5,color:'#6676c8',symbol:'·',mood:'Immensité noire, vide spatial, vertige.',description:'« Macrovoid » explore le vide intérieur, le deuil du père et la crise de foi de Ramsès24, qui transforme peu à peu sa douleur en mélodie et en résilience.'},
  {id:'am-stram-gram',number:20,title:'Am-Stram-Gram',artist:'Savas ft Ramsès24',chapter:'V — Le vide et le jeu',chapterId:5,color:'#edbf4a',symbol:'✣',mood:'Jeu, choix, hasard, couleurs et mouvement.',description:'« Am-Stram-Gram » est un feat de trap drill sombre entre Ramsès24 et Savas, où le hasard devient le déclencheur d’un face-à-face brutal, chargé de basses, de provocation et d’énergie de rue.'}
];
tracks.push({id:'carre',number:21,title:'Carré',artist:'Ramsès24',chapter:'Bonus / Hors orbite',chapterId:0,color:'#c28a5b',symbol:'□',mood:'After-party, victoire, lumière et remerciement.',description:'« Carré (Bonus) » célèbre la fin de l’album avec confiance, humour et gratitude, en rendant hommage aux proches, aux soutiens, à Savas, à Suno et aux efforts de Ramsès24.'});
const visualPaths = {
  omen:'Image de fond/Omen.png',
  heartbreak:'Image de fond/Heartbreak.png',
  deroute:'Image de fond/Deroute.png',
  'only-on-the-night':'Image de fond/Only on the nignht.png',
  ramses24:'Image de fond/Ramses24.png',
  'ah-bah-wsh':'Image de fond/Ah bah wersh oft.png',
  'on-est-pas-pareil':'Image de fond/On est pas pareil .png',
  '14-fevrier':'Image de fond/14 Fevrier.png',
  'faux-frere':'Image de fond/Fauxfrere.png',
  'avant-ton-depart':'Image de fond/Avant ton départ.png',
  'paranormal-r24':'Image de fond/Paranormal R24.png',
  'who-are-you-bella':'Image de fond/Bella.png',
  mutonchaku:'Image de fond/Mutonchaku.png',
  'la-vie-est-hard':'Image de fond/la vie est hard.png',
  'la-melo-24':'Image de fond/La melo24.png',
  'ma-vie-html':'Image de fond/Ma vie.html.png',
  oklm:'Image de fond/OKLM.png',
  commoner:'Image de fond/Commoner.png',
  macrovoid:'Image de fond/Macrovoid.png',
  'am-stram-gram':'Image de fond/am-stram-gram.png',
  carre:'Image de fond/Carre.jpg'
};
const audioPaths = {
  omen:'audio/omen.mp3',
  heartbreak:'audio/heatbreak.mp3',
  deroute:'audio/deroute.mp3',
  'only-on-the-night':'audio/only-on-the-night.mp3',
  ramses24:'audio/Ramses24.mp3',
  'ah-bah-wsh':'audio/Ah-bah-wersh.mp3',
  'on-est-pas-pareil':'audio/On est pas pareil.mp3',
  '14-fevrier':'audio/14 fevrier.mp3',
  'faux-frere':'audio/faux-frère.mp3',
  'avant-ton-depart':'audio/Avant ton depart .mp3',
  'paranormal-r24':'audio/paranormal-r-2-4.mp3',
  'who-are-you-bella':'audio/bella .mp3',
  mutonchaku:'audio/Mutonchaku.mp3',
  'la-vie-est-hard':'audio/la-vie-est-hard.mp3',
  'la-melo-24':'audio/melo24 .mp3',
  'ma-vie-html':'audio/ma-vie.html .mp3',
  oklm:'audio/who are you ramses (oklm) .mp3',
  commoner:'audio/Commoner.mp3',
  macrovoid:'audio/Macrovoid .mp3',
  'am-stram-gram':'audio/am-stram-gram.mp3',
  carre:'audio/bonus .mp3'
};
tracks.forEach(track=>{track.visual=visualPaths[track.id]||''; track.audio=audioPaths[track.id]||`audio/${track.id}.mp3`; track.lyrics=''; track.locked=false;});
const chapters = [{id:1,title:'Les signes',subtitle:'Présage → douleur → déplacement'},{id:2,title:'L’identité',subtitle:'Le nom, le masque, le miroir'},{id:3,title:'Les mémoires et les fantômes',subtitle:'Ce qui reste quand la lumière change'},{id:4,title:'Le système',subtitle:'Le réel comme interface'},{id:5,title:'Le vide et le jeu',subtitle:'Vertige → libération'}];
const moods = {amour:[1,8,15],colere:[2,14,18],solitude:[2,10,19],nostalgie:[8,10,13],motivation:[5,14,16],confusion:[3,7,12],curiosite:[1,11,17],paix:[4,13,15]};
let activeIndex=0; let audio=null; let isPlaying=false; let favorites=JSON.parse(localStorage.getItem('r24-favorites')||'[]'); let listened=JSON.parse(localStorage.getItem('r24-listened')||'[]');
const $ = selector => document.querySelector(selector); const $$ = selector => [...document.querySelectorAll(selector)];
function trackByNumber(number){return tracks.find(track=>track.number===number)||tracks[0]}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('is-visible');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('is-visible'),3300)}
function renderChapters(){const map=$('#chapterMap');map.innerHTML=chapters.map(chapter=>{const items=tracks.filter(track=>track.chapterId===chapter.id);return `<section class="chapter" aria-labelledby="chapter-${chapter.id}"><div class="chapter-head"><span class="chapter-label">CHAPITRE ${['I','II','III','IV','V'][chapter.id-1]}</span><h3 id="chapter-${chapter.id}">${chapter.title}</h3></div><p class="chapter-subtitle">${chapter.subtitle}</p><div class="track-row">${items.map(track=>`<button class="track-node ${listened.includes(track.id)?'is-listened':''}" style="--track-color:${track.color};--track-image:url('${track.visual}')" data-track="${track.number}" type="button"><span class="track-number">${String(track.number).padStart(2,'0')}</span><span class="track-title">${track.title}</span><span class="track-desc">${track.description}</span><span class="track-symbol">${track.symbol}</span></button>`).join('')}</div></section>`}).join(''); $$('.track-node').forEach(node=>node.addEventListener('click',()=>openTrack(Number(node.dataset.track))));}
function openTrack(number){activeIndex=tracks.findIndex(track=>track.number===number);const track=tracks[activeIndex];const chapterLabel=track.chapterId?`CHAPITRE ${['I','II','III','IV','V'][track.chapterId-1]} / ${track.chapter.replace(/^[IVX]+ — /,'')}`:'BONUS / HORS ORBITE';document.body.classList.add('panel-open');$('#trackPanel').classList.add('is-open');$('#trackPanel').setAttribute('aria-hidden','false');$('#panelArt').style.setProperty('--panel-color',track.color);$('#panelArt').style.background=`linear-gradient(180deg,rgba(14,8,7,.16),rgba(14,8,7,.72)),url("${track.visual}"),radial-gradient(circle at 40% 35%,${track.color},transparent 25%),#09080e`;$('#panelNumber').textContent=String(track.number).padStart(2,'0');$('#panelChapter').textContent=chapterLabel;$('#panelTitle').textContent=track.title;$('#panelMood').textContent=track.mood;$('#panelIndex').textContent=`${String(track.number).padStart(2,'0')} / ${tracks.length}`;$('#panelStatus').textContent='FICHIER AUDIO EN ATTENTE';$('#panelFavorite').textContent=favorites.includes(track.id)?'♥':'♡';updatePlayer();}
function closeTrack(){document.body.classList.remove('panel-open');$('#trackPanel').classList.remove('is-open');$('#trackPanel').setAttribute('aria-hidden','true')}
function updatePlayer(){const track=tracks[activeIndex];const chapterLabel=track.chapterId?`Chapitre ${['I','II','III','IV','V'][track.chapterId-1]} — ${track.chapter.split(' — ')[1]||track.chapter}`:'Bonus — Hors orbite';$('#miniTitle').textContent=track.title;$('#miniChapter').textContent=chapterLabel;$('#miniArt').style.background=`linear-gradient(135deg,rgba(14,8,7,.2),rgba(14,8,7,.62)),url("${track.visual}"),radial-gradient(circle,${track.color},#110d18 65%)`;$('#miniArt span').textContent=String(track.number).padStart(2,'0');$('#immersiveTitle').textContent=track.title;$('#immersiveDescription').textContent=track.description;$('#immersiveArt').style.setProperty('--panel-color',track.color);$('#immersiveArt').style.background=`linear-gradient(180deg,rgba(14,8,7,.1),rgba(14,8,7,.55)),url("${track.visual}"),radial-gradient(circle at 40% 35%,${track.color},transparent 26%),#12101d`;$('#immersiveArt span').textContent=String(track.number).padStart(2,'0');$('#miniPlay').textContent=isPlaying?'Ⅱ':'▶';$('#immersivePlay').textContent=isPlaying?'Ⅱ':'▶';$('#immersiveFavorite').textContent=favorites.includes(track.id)?'♥':'♡';$('#immersiveFavorite').setAttribute('aria-label',favorites.includes(track.id)?'Retirer des favoris':'Ajouter aux favoris')}
function markListened(track){if(!listened.includes(track.id)){listened.push(track.id);localStorage.setItem('r24-listened',JSON.stringify(listened));renderChapters()}}
function loadAudio(track){audio=$('#audioEngine');audio.pause();audio.src=track.audio;audio.dataset.trackId=track.id;audio.addEventListener('loadedmetadata',()=>{$('#duration').textContent=formatTime(audio.duration)},{once:true});audio.addEventListener('timeupdate',()=>{$('#progress').value=audio.duration?(audio.currentTime/audio.duration)*100:0;$('#elapsed').textContent=formatTime(audio.currentTime)});audio.addEventListener('ended',()=>{isPlaying=false;updatePlayer();nextTrack()},{once:true});audio.load()}
function togglePlay(){const track=tracks[activeIndex];if(!track.audio){markListened(track);showToast(`« ${track.title} » est prêt pour ton fichier audio dans audio/.`);openImmersive();return}if(!audio||audio.dataset.trackId!==track.id)loadAudio(track);isPlaying=!isPlaying;if(isPlaying)audio.play().catch(()=>{isPlaying=false;updatePlayer();showToast('Lecture bloquée : ouvre le projet via un serveur local (ex. http://localhost:8000) pour écouter les fichiers audio.')});else audio.pause();updatePlayer()}
function nextTrack(step=1){activeIndex=(activeIndex+step+tracks.length)%tracks.length;if(audio){audio.pause();audio=null}isPlaying=false;$('#progress').value=0;$('#elapsed').textContent='00:00';$('#duration').textContent='--:--';updatePlayer();markListened(tracks[activeIndex]);showToast(`Fragment ${String(tracks[activeIndex].number).padStart(2,'0')} — ${tracks[activeIndex].title}`)}
function openImmersive(){document.body.classList.add('panel-open');$('#immersivePlayer').classList.add('is-open');$('#immersivePlayer').setAttribute('aria-hidden','false');updatePlayer();loadComments()}
function closeImmersive(){document.body.classList.remove('panel-open');$('#immersivePlayer').classList.remove('is-open');$('#immersivePlayer').setAttribute('aria-hidden','true')}
function toggleImmersiveFavorite(){const track=tracks[activeIndex];favorites=favorites.includes(track.id)?favorites.filter(id=>id!==track.id):[...favorites,track.id];localStorage.setItem('r24-favorites',JSON.stringify(favorites));updatePlayer();showToast(favorites.includes(track.id)?`« ${track.title} » ajouté aux favoris.`:`« ${track.title} » retiré des favoris.`)}
function escapeHTML(value){return value.replace(/[&<>'"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]))}
function localComments(){return JSON.parse(localStorage.getItem(`r24-comments-${tracks[activeIndex].id}`)||'[]')}
function renderComments(comments=localComments()){const list=$('#commentList');list.innerHTML=comments.length?comments.map(comment=>`<article class="comment-item"><span class="comment-author">${escapeHTML(comment.name||'Anonyme')}</span><p class="comment-body">${escapeHTML(comment.text)}</p></article>`).join(''):'<p class="comment-empty">Aucun commentaire pour ce son. Sois le premier à laisser une trace.</p>'}
async function loadComments(){try{const response=await fetch(`/api/comments?track=${encodeURIComponent(tracks[activeIndex].id)}`);if(!response.ok)throw new Error('Comments API unavailable');const data=await response.json();renderComments(data.comments)}catch{renderComments()}}
async function submitComment(event){event.preventDefault();const text=$('#commentText').value.trim();if(!text)return;const name=$('#commentName').value.trim()||'Anonyme';const trackId=tracks[activeIndex].id;try{const response=await fetch(`/api/comments?track=${encodeURIComponent(trackId)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,text})});if(!response.ok)throw new Error('Comments API unavailable');const data=await response.json();event.target.reset();renderComments(data.comments);showToast('Commentaire publié pour tout le monde.');}catch{const key=`r24-comments-${trackId}`;const comments=JSON.parse(localStorage.getItem(key)||'[]');comments.unshift({name,text});localStorage.setItem(key,JSON.stringify(comments));event.target.reset();renderComments(comments);showToast('Commentaire enregistré sur cet appareil.');}}
function selectMood(mood){$$('[data-mood]').forEach(button=>button.classList.toggle('is-selected',button.dataset.mood===mood));const chosen=moods[mood].map(trackByNumber);$('#moodResult p').textContent=chosen.map(track=>`${String(track.number).padStart(2,'0')} ${track.title}`).join('  ·  ');$('#moodResult .result-line').style.background=chosen[0].color;showToast(`Parcours ${mood} synchronisé.`)}
function formatTime(seconds){if(!Number.isFinite(seconds))return'--:--';return`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(Math.floor(seconds%60)).padStart(2,'0')}`}
function setupBackToTop(){const button=$('#backTop');window.addEventListener('scroll',()=>button.classList.toggle('is-visible',window.scrollY>420),{passive:true});button.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}))}
function init(){setupBackToTop();setTimeout(()=>$('#bootScreen').classList.add('is-done'),900);renderChapters();updatePlayer();$$('[data-scroll]').forEach(button=>button.addEventListener('click',()=>document.getElementById(button.dataset.scroll).scrollIntoView({behavior:'smooth'})));$('#closeTrack').addEventListener('click',closeTrack);$('#panelPlay').addEventListener('click',()=>{closeTrack();togglePlay()});$('#miniPlay').addEventListener('click',togglePlay);$('#immersivePlay').addEventListener('click',togglePlay);$('#miniNext').addEventListener('click',()=>nextTrack());$('#immersiveNext').addEventListener('click',()=>nextTrack());$('#miniPrevious').addEventListener('click',()=>nextTrack(-1));$('#immersivePrevious').addEventListener('click',()=>nextTrack(-1));$('#openImmersive').addEventListener('click',openImmersive);$('#closeImmersive').addEventListener('click',closeImmersive);$('#launchAlbum').addEventListener('click',()=>{activeIndex=0;openImmersive();togglePlay()});$('#panelFavorite').addEventListener('click',()=>{const track=tracks[activeIndex];favorites=favorites.includes(track.id)?favorites.filter(id=>id!==track.id):[...favorites,track.id];localStorage.setItem('r24-favorites',JSON.stringify(favorites));$('#panelFavorite').textContent=favorites.includes(track.id)?'♥':'♡';showToast(favorites.includes(track.id)?'Fragment ajouté à ta constellation.':'Fragment retiré de ta constellation.')});$$('[data-mood]').forEach(button=>button.addEventListener('click',()=>selectMood(button.dataset.mood)));$('#bonusTrack').addEventListener('click',event=>{event.stopPropagation();openTrack(21)});$('.bonus-zone').addEventListener('click',()=>openTrack(21));$('#reduceMotion').addEventListener('click',()=>{document.body.classList.toggle('reduced-motion');showToast(document.body.classList.contains('reduced-motion')?'Animations réduites.':'Animations réactivées.')});$('#progress').addEventListener('input',event=>{if(audio&&audio.duration)audio.currentTime=(event.target.value/100)*audio.duration});document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeTrack();closeImmersive()}if(event.code==='Space'&&event.target.tagName!=='TEXTAREA'){event.preventDefault();togglePlay()}})}
document.addEventListener('DOMContentLoaded',init);
document.addEventListener('DOMContentLoaded',()=>{$('#immersiveFavorite').addEventListener('click',toggleImmersiveFavorite);$('#panelPlay').addEventListener('click',openImmersive);$('#immersiveNext').addEventListener('click',loadComments);$('#immersivePrevious').addEventListener('click',loadComments);$('#commentForm').addEventListener('submit',submitComment)});